Update README.adoc
kabanero-io/guide-app-logging pull request #18
Opened 2020-02-05 16:29 UTC by t-koman

per #267 of docs repo

2020-02-13 00:33 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kabanero-io/guide-app-logging-okd-3.11?pullRequest=18) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kabanero-io/guide-app-logging-okd-3.11?pullRequest=18) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kabanero-io/guide-app-logging-okd-3.11?pullRequest=18) it.</sub>

2020-02-13 16:46 UTC, t-koman commented
Hello,
I have signed the CLA.
thanks,
Tom

IBM - WebSphere Application Server Information DevelopmentBuilding 707, Floor 1, Office H612455 South Road, Poughkeepsie, NY 12601T/L: 8-295-8668 PHONE: (845) 435-8668tkoman@us.ibm.com
 
 
----- Original message -----From: CLA assistant <notifications@github.com>To: "kabanero-io/guide-app-logging-okd-3.11" <guide-app-logging-okd-3.11@noreply.github.com>Cc: t-koman <tkoman@us.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [kabanero-io/guide-app-logging-okd-3.11] Update README.adoc (#18)Date: Wed, Feb 12, 2020 7:33 PM 
Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us recheck it.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
 

2020-02-14 02:05 UTC, t-koman commented
@fwji Frank - please review my terminology update.  Your review is pending...... thanks

2020-02-18 05:48 UTC, fwji requested changes

2020-02-18 05:48 UTC, fwji commented on README.adoc
> +Use the ansible-playbook located in the https://github.com/openshift/openshift-ansible/tree/release-3.11[openshift-ansible] repository to install EFK stacks on a Kubernetes development cluster. Then
I don't think we can replace OKD here with Kubernetes. The ansible script is only for a OKD cluster.

2020-02-18 05:48 UTC, fwji commented on README.adoc
> +**EFK (Elasticsearch, FluentD, and Kibana)** is a log aggregation tool, and this guide describes the process of deploying EFK using the ansible-playbook script provided by Kubernetes development (The
OKD is the acronym for (The Origin Community Distribution of Kubernetes), so cannot be simply replaced by Kubernetes

2020-02-18 05:48 UTC, fwji commented on README.adoc
> +Installing EFK on Kubernetes development requires an https://docs.okd.io/3.11/install/configuring_inventory_file.html[inventory host file] and the openshift-ansible playbook for logging the installat
similarly, I would use OKD here as the playbook is OKD exclusive

2020-02-18 05:48 UTC, fwji commented on README.adoc
> +Numerous Ansible variables are available to fine tune the EFK stack. Detailed information about the installation and configuration can be found in Kubernetes development documentation https://docs.ok
Kubernetes -> OKD

2020-02-18 05:48 UTC, fwji commented on README.adoc
> +* `openshift_logging_es_memory_limit` and `openshift_logging_es_ops_memory_limit` are self-explanatory and can be set according to your preference. For stable operation, allocate at least 2 GB of mem
Kubernetes development -> OKD

2020-02-18 05:48 UTC, fwji commented on README.adoc
> +After all the variables are set in the inventory file, run the ansible-playbook command to install the EFK stack onto its current Kubernetes development cluster.
Kubernetes development -> OKD

2020-02-18 05:51 UTC, fwji commented
Hi @t-koman, please let me know if there are any concerns for using OKD in the guide. A lot of the material communicated in this guide is OKD exclusive, and the content does not apply to Kubernetes.

2020-02-19 18:23 UTC, jantley-ibm commented
@fwji @t-koman has made updates per your last review, if you agree with the changes please approve the review so that we can merge -- thanks

2020-02-19 18:31 UTC, fwji approved these changes

2020-02-19 18:44 UTC, merged